/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransformRouteImport } from './routes/transform'
import { Route as SafeImagesRouteImport } from './routes/safe-images'
import { Route as SafeAudioRouteImport } from './routes/safe-audio'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as LiveRouteImport } from './routes/live'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeImagesRoute = SafeImagesRouteImport.update({
  id: '/safe-images',
  path: '/safe-images',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeAudioRoute = SafeAudioRouteImport.update({
  id: '/safe-audio',
  path: '/safe-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/live': typeof LiveRoute
  '/meet': typeof MeetRoute
  '/safe-audio': typeof SafeAudioRoute
  '/safe-images': typeof SafeImagesRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/live': typeof LiveRoute
  '/meet': typeof MeetRoute
  '/safe-audio': typeof SafeAudioRoute
  '/safe-images': typeof SafeImagesRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/live': typeof LiveRoute
  '/meet': typeof MeetRoute
  '/safe-audio': typeof SafeAudioRoute
  '/safe-images': typeof SafeImagesRoute
  '/transform': typeof TransformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/create'
    | '/live'
    | '/meet'
    | '/safe-audio'
    | '/safe-images'
    | '/transform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/create'
    | '/live'
    | '/meet'
    | '/safe-audio'
    | '/safe-images'
    | '/transform'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/create'
    | '/live'
    | '/meet'
    | '/safe-audio'
    | '/safe-images'
    | '/transform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  CreateRoute: typeof CreateRoute
  LiveRoute: typeof LiveRoute
  MeetRoute: typeof MeetRoute
  SafeAudioRoute: typeof SafeAudioRoute
  SafeImagesRoute: typeof SafeImagesRoute
  TransformRoute: typeof TransformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-images': {
      id: '/safe-images'
      path: '/safe-images'
      fullPath: '/safe-images'
      preLoaderRoute: typeof SafeImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-audio': {
      id: '/safe-audio'
      path: '/safe-audio'
      fullPath: '/safe-audio'
      preLoaderRoute: typeof SafeAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  CreateRoute: CreateRoute,
  LiveRoute: LiveRoute,
  MeetRoute: MeetRoute,
  SafeAudioRoute: SafeAudioRoute,
  SafeImagesRoute: SafeImagesRoute,
  TransformRoute: TransformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
